modLoader="javafml"
loaderVersion="[35,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Caves/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves"
logoFile="BCLogo.png"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	updateJSONURL="https://raw.githubusercontent.com/yungnickyoung/YUNGs-Better-Caves/1.16/versions.json"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"

[[dependencies.bettercaves]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bettercaves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"